version: '3.3'
services:
    sonarr:
        container_name: sonarr
        restart: unless-stopped
        ports:
            - '127.0.0.1:8989:8989'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Etc/NZST
        volumes:
            - '/mnt/c/dev/servarr/sonarr/config:/config'
            - '/mnt/x:/data'
            - '/mnt/y:/data-y'
        image: cr.hotio.dev/hotio/sonarr
    radarr:
        container_name: radarr
        restart: unless-stopped
        ports:
            - '127.0.0.1:7878:7878'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Etc/NZST
        volumes:
            - '/mnt/c/dev/servarr/radarr/config:/config'
            - '/mnt/x:/data'
            - '/mnt/y:/data-y'
        image: cr.hotio.dev/hotio/radarr
    qbittorrent:
        container_name: qbittorrent
        restart: unless-stopped
        ports:
            - '127.0.0.1:8080:8080'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Etc/NZST
        volumes:
            - '/mnt/c/dev/servarr/qbittorrent/config:/config'
            - '/mnt/x:/data'
            - '/mnt/y:/data-y'
        image: cr.hotio.dev/hotio/qbittorrent
    prowlarr:
        container_name: prowlarr
        restart: unless-stopped
        ports:
            - '127.0.0.1:9696:9696'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=Etc/NZST
        volumes:
            - '/mnt/c/dev/servarr/prowlarr:/config'
        image: 'hotio/prowlarr:testing'